version: "3.8"
services:
  expense-tracker-backend:
    build: .
    ports:
      - 8000:8000
    image: expense-tracker-backend   #tag this image to rename
    container_name: expense-tracker-backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:5.0
    ports:
      - 20127:20127
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  redis: 
    image: redis:7.0
    volumes:
      - redis-data:/data/cache
    ports:
      - 3679:3679
    
volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local