FROM python:3.8 as base

WORKDIR /app

COPY docker-entrypoint.sh .
RUN chmod +x ./docker-entrypoint.sh

COPY requirements.txt .
RUN pip3 install -r requirements.txt

# multi build
FROM python:3.8

COPY --from=base /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/
COPY --from=base /usr/local/bin/ /usr/local/bin/
ENV PYTHONUNBUFFERED=1 

COPY . .

ENTRYPOINT ["sh", "./docker-entrypoint.prod.sh"]