# Generated by Django 4.0.2 on 2022-03-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='Transaction',
        ),
    ]
