# Generated by Django 4.0.2 on 2022-04-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='t_date',
        ),
    ]
