# Generated by Django 4.0.2 on 2022-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_transaction_t_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_date',
            field=models.DateField(),
        ),
    ]
