# Generated by Django 4.0.2 on 2022-04-24 00:05

import django.core.exceptions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', validators=[django.core.exceptions.ObjectDoesNotExist], verbose_name='category'),
        ),
    ]
