# Generated by Django 4.0.2 on 2022-04-07 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_t_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
