# Generated by Django 4.0.2 on 2022-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_t_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_date',
            field=models.DateTimeField(),
        ),
    ]
