# Generated by Django 4.0.2 on 2022-04-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_t_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=50),
        ),
    ]
